In [9]:
pip install numpy

You should consider upgrading via the 'C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Task 1
Create a 1D array of numbers from 0 to 9​

In [2]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Task 2
Create a 3×3 NumPy array of all Boolean value Trues​

In [3]:
b = np.array([[[True,True,True],[True,True,True],[True,True,True]]]) #using a 3D Matrix
print(b.ndim)
print(b)

3
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


Task 3
Extract all odd numbers from array of 1-10​

In [4]:
c = np.arange(1,10)
c = [i for i in c if i % 2 == 1] #used a loop to find the odd numbers
print(c)

[1, 3, 5, 7, 9]


Task 4
Replace all odd numbers in an array of 1-10 with the value -1​

In [5]:
d = np.arange(1,10)
for i in d:
    if i % 2 == 1: #used a loop to find odd numbers
        d[i] = -1 #find the position of the odd numbers and replace them with -1
print(d)

[ 1 -1  3 -1  5 -1  7 -1 -1]


Task 5
Convert a 1D array to a 2D array with 2 rows​

In [6]:
e = np.arange(1,11) #single 1D array e
print(e)
e = np.array([[1,2,3,4,5],#converted e into a 2D array with 2 rows
             [6,7,8,9,10]])
print(e)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Task 6
Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals​

In [7]:
a = np.arange(9).reshape(3,3) #reshape helps group them in 2D arrays
b = np.arange(10,19).reshape(3,3)
c = np.dot(a,b)#np.dot multiplies each element within the matrix
d = np.sum(c)#np.sum sums the total elements in the array
print(c)
print(d)

[[ 45  48  51]
 [162 174 186]
 [279 300 321]]
1566


Task 7
Create the following pattern without hardcoding. Use only NumPy functions.​

In [22]:
## Create 111222333123123123 without hardcording ####
a = np.array ([[[[[1,1,1],
             [2,2,2],
             [3,3,3],
             [1,2,3],
             [1,2,3],
             [1,2,3]]]]]) ## here we created a 6 dimensional array to give us the number needed ###
             
print(a.flatten()) ## used the flattened object to create a 1 dimensional array


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


Task 8
In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating  items present in array b​

In [5]:
import numpy as np

In [4]:
import numpy as np
a = np.arange(1,6) #create a range to display 1 - 5
b = np.arange(4,10) #create a range to display 4 - 10
c = [] #created an empty list C
d = [] #created an empty list C

for i in b: #looping through b
        if i not in a:#checking if each element of b is in a
            c.append(i)#if i is not in a then append to c
b = np.array(c) #changing the values of b to an array of c as c no longer holds the matching elements in b
print(b)


[6 7 8 9]


Task 9
Get all items between 3 and 7 from a and b and sum them together​

In [7]:
for i in a:#loop through a
    if i == 3 or i == 4 or i == 5:#check if it matches 3 4 or 5
        d.append(i)#append to empty list d where it matches
for i in b: #loop through b
    if i == 6 or i == 7: #check if it matches 6 or 7
        d.append(i) #append to empty list d where it matches
s_array = np.array(d) #change d from a list to an array
sum_array = sum(s_array) # sum the values in the array
print(s_array)
print(sum_array)

[3 4 5]
12
